name: edu
favicon: null
layout_spectrum: 0.8839898556470871
typography_spectrum: 0.44286760664545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9339070364367217
  lightness: 0.31947226519696414
  saturation: 0.08480982040055096
  rhythmicContrast: 0.18244873825460672
purpose: []
